### ISSUE TITLE
Problem with Menus and Popup windows

### ISSUE THREAD

**Issue by lschaffer** [alump/GoFullScreen#4]
After switching to fullscreen some element does not work anymore like menu (submenus would not be opened), popup windows, will be a fix for this issue ?
Vaadin 7.6.4

**Comment by alump** [comment]
Sorry this can't be fixed. Issue here is that HTML5 fullscreen API takes DOM element, and then shows everything inside that element. Components like Windows, Popups etc. by default inject new DOM element to the top of the HTML tree. So those will be only visible if you fullscreen the whole application.

Only workaround to this would be to use components that inject popups etc inside the element of the widget itself. Normal Vaadin components do not behave this way sadly.

**Comment by alump** [comment]
Closing as this can not be fixed.
